In [6]:
#  Initialize with zeros

import numpy as np

data = np.zeros([2,3])

print(data)

print(type(data))


#  Initialize with zeros example 2 


data_2 = np.zeros([4,4])

print(data_2)

print(type(data_2))


[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
