In [5]:
# Two dimension 

data = np.array([[1,2,3,4],[5,6,7,8]])

print(data)

print("Dimensions :" , data.ndim)

[[1 2 3 4]
 [5 6 7 8]]
Dimensions : 2


In [2]:
# One dimension 
import numpy as np
data = np.array([1,2,3,4,5])

print(data)

print("Dimensions : " , data.ndim)

[1 2 3 4 5]
Dimensions :  1


In [1]:
import numpy as np

# Zero dimension 

n = np.array(25)

print("Dimensions : " , n.ndim)



Dimensions :  0


In [3]:
# create an array by passing tuple

data = np.array([1,2,3,4])

print(data)

[1 2 3 4]


In [6]:
import numpy as np

# create an array by passing list 

data = np.array((1,2,3,4))

print(data)


[1 2 3 4]
