In [86]:
# logs_Data = np.log(data_1)

# print(logs_Data)


print(f"Square of root :  " ,(data_1 ** 2) )

print( f" Square of root :", (data_2 ** 3 ) )

Square of root :   [   0  400  900 1600]
 Square of root : [[1331 1728 2197]
 [2744 3375 4096]
 [4913 5832 6859]]


In [52]:
np.eye(1,6)

array([[1., 0., 0., 0., 0., 0.]])

In [59]:
data = np.arange(1,26).reshape(5,5)

print(data)

print(data[:2 , 1:5], "\n")
print(data[0:2,0:3] , "\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 2  3  4  5]
 [ 7  8  9 10]] 

[[1 2 3]
 [6 7 8]] 



In [51]:
print(np.random.rand(1,58).shape)

(1, 58)


In [50]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
data = np.arange(1,26).reshape(5,5)

print(data)

print(data[1:2,1:6])

print(data[1:4,1:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9 10]]
[[ 7]
 [12]
 [17]]


In [ ]:
import numpy as np 

data = np.arange(1,10).reshape(3,3)

data_2 = np.arange(11,20).reshape(3,3)

print(data)

print(data_2)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


array([[121, 144, 169],
       [196, 225, 256],
       [289, 324, 361]])

In [31]:
import numpy as np 

data = np.arange(1,10,)



print(data[::-1])



[9 8 7 6 5 4 3 2 1]


In [25]:
import numpy as np 

data = np.array([[[10,20,30,40],
                 [50,60,70,80],
                 [20,30,40,50]]])


print(np.sum(data))

print(data.ndim)



500
3


In [22]:
import numpy as np 


data = np.array([
    [ 10,20,30,40],
    [50,60,70,80]])

print(np.sum(data))

print(data.ndim)


360
2


In [4]:
import numpy as np 

data = np.array([10,20,30,40])

print(np.median(data))

25.0


In [11]:
import numpy as np 
from statistics import mode


data = np.array([10,20,30,40,40,40])



print(mode(data))


40


In [3]:
import numpy as np 

data = np.array([10,20,30,40])

print(np.mean(data))

25.0
