In [ ]:
import numpy as np 


arr = np.zeros((8,8))



# for i in range(0,8):
#     if i % 2 == 0:
#         arr[i, ::2] = 0
        

#     else:
#         arr[i,1::2] = 0

arr[1::2,::2] = 1

arr[::2 , 1::2] = 1
        
print(arr)





[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [9]:
#1. create the following 8x8 matrix

import numpy as np 

arr = np.zeros((8,8))

arr[1::2 , ::2] = 1

arr[::2 , 1::2] = 1

print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [30]:
# 2. create a 5x5 matrix where the border contains 1s and the inside contains 0s

arr = np.zeros((5,5))

arr[0:1 , : ] = 1

arr[4: , :]  = 1

arr[1:: , ::4] = 1

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
# 3 .reeplace values 

# given : 

arr = np.array([5,12,7,18,25,3,15])

print(np.where(arr > 10,-1,arr))

[ 5 -1  7 -1 -1  3 -1]


In [45]:
# 4 . Extract multiples of 3 

# create an array from 1 to 100 and extract only numbers divisible 3 


arr = np.arange(0,101)
# print(arr)

print(np.where(arr % 3 == 0))

(array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]),)


In [47]:
# 5 find common elements 

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

print(np.intersect1d(a,b))

[4 5]


In [60]:
# 6. Find missing numbers 

arr = np.array([1,2,4,6,7,9])

arr.max()
arr.min()

b = np.arange(1,10)

print(np.setdiff1d(b,arr))


[3 5 8]


In [ ]:
# 7. Row-wise Maximum 

# Find the maximum value from each row :

arr = np.array([[1,2,3],[4,5,6,],[7,8,9]])

print(arr, '\n')
print(np.max(arr,axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[3 6 9]
[7 8 9]


In [72]:
# 8. Columnn wise sum 

arr = np.array([[4,8,2],[9,1,5],[7,6,3]])

print(np.sum(arr,axis=0))

[20 15 10]


In [81]:
# 9. Matrix multiplication

a = np.array([[1,2],[3,4]])

b = np.array([[5,6],[7,8]])

print(a@b)


[[19 22]
 [43 50]]


In [86]:
# 10. Flatten a matrix

arr = np.arange(1,17).reshape(4,4)

print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [88]:
# 11. Reshape without changing data 

arr = np.arange(24).reshape(2,3,4)

print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [94]:
# 12. Reverse each row 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)
# print(arr[::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [109]:
# 13 . Reverse each column

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr[::-1 , ::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [116]:
# 14. Sort an array 

arr = np.array([10,5,20,15,8,3])

print(np.sort(arr))

[ 3  5  8 10 15 20]


In [118]:
# 15 . Sort row wise 

arr = np.array([[9,4,7],[2,8,1],[6,3,5]])

print(np.sort(arr,axis=1))

[[4 7 9]
 [1 2 8]
 [3 5 6]]


In [120]:
# 16 . find indices where numbers are even 

arr = np.array([11,22,35,40,55,60])

print(np.where(arr %  2 ==0))

(array([1, 3, 5]),)


In [124]:
# 17. Count unique elements 

arr = np.array([1,2,2,3,4,4,5,5,5])

count = np.unique(arr)

print(len(count))


5


In [126]:
# 18. Frequency of elements 

arr = np.array([1,2,2,2,3,4,4,5,5,5])

print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5]), array([1, 3, 1, 2, 3]))


In [130]:
# 19. Normalise an array 

arr = np.array([10,20,30,40,50])

max = arr.max()
min = arr.min()

min_max = (arr-min)/(max-min)

print(min_max)



[0.   0.25 0.5  0.75 1.  ]


In [146]:
# 20. Generate random integers

arr = np.random.randint(1,101,25)

shape = arr.reshape(5,5)

print(shape)

[[ 6 45 53 98 29]
 [44 23 19  8 51]
 [77 87 10 58 34]
 [ 3 77 93 89 52]
 [42 78 45 56 89]]


In [155]:
# 21. find second largest integer

arr = np.array([10,50,20,80,60,90])

a = np.sort(arr)

print(a[4])




80


In [168]:
# 22 . Find Duplicate element

arr = np.array([1,2,3,4,2,5,6,9,9,4,1,7])

v,c = np.unique(arr,return_counts=True)

# print(v,c)

print(v[c>1])

[1 2 4 9]


In [170]:
# 23 . Diagnal sum 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

a = np.diag(arr)

print(np.trace(arr))

# print(np.sum(a))

15


In [175]:
# 24. Create multiplication table 

nums = np.arange(1,11)

# print("Original Matrix : ",nums)

# print("Row Matrix : ",nums[np.newaxis, :])


# print("Column Matrix : ",nums[:,np.newaxis])

multiplication_table = nums* nums[:,np.newaxis]

print(multiplication_table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [2]:
a = 0.1
b =0.2
c = a+b
print(c)

0.30000000000000004
