In [ ]:
# 1. Create a numpy array

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 2. Check array property 

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(np.ndim(arr))
print(np.size(arr))
print(np.shape(arr))
print(arr.dtype)



1
10
(10,)
int64


In [9]:
# 3. create a zeros array

arr = np.zeros([3,3])

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# 4. create a ones array

arr = np.ones([4,2])

print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
# 5 create a 5x5 identity matrix

arr = np.identity((5),dtype=int)

print(arr)




[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
# 6. create a range array 

arr = np.arange(10,51,5)

print(arr)

[10 15 20 25 30 35 40 45 50]


In [35]:
# 7. create evenly spaced value

arr = np.linspace(0,100,11)

print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
# 8.Reshape an array 3x4

arr = np.arange(1,13).reshape(3,4)

print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
# 9. create an element and print its first element 

arr =  np.array([1,2,3,4,5,6,7,8,9])

print(arr[0])

1


In [127]:
# 10. create an element and print its last element 

arr =  np.array([1,2,3,4,5,6,7,8,9])

print(arr[-1])

9


In [ ]:
# 11.  slice an array 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])

print(arr[5:11])

[ 6  7  8  9 10]


In [ ]:
# 12. reverse an array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])

print(arr[::-1])

[21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
# 13. create an array and find its maximum value


arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])

print(np.max(arr))

21


In [50]:
# 14. find minimum value

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])

print(np.min(arr))

1


In [51]:
# 15. calculate sum

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])

print(np.sum(arr))


231


In [52]:
# 16 . calculate mean 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])

print(np.mean(arr))

11.0


In [ ]:
# 17. calculate median 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])

print(np.median(arr))

In [53]:
# 18. find standard deviation

arr = np.array([5,10,15,20,25])

print(np.std(arr))

7.0710678118654755


In [ ]:
# 19. add two arrays

arr_1 = np.array([[1,2,3]])
arr_2 = np.array([[4,5,6]])


print(np.add(arr_1,arr_2))

[[5 7 9]]


In [ ]:
# 20. multiply two arrays

arr_1 = np.array([[2,4,6]])
arr_2 = np.array([[4,5,6]])

print(np.multiply(arr_1,arr_2))

[[ 8 20 36]]


In [64]:
# 21. multiply two arrays

arr = np.arange(1,11)

print(np.square(arr))

[  1   4   9  16  25  36  49  64  81 100]


In [ ]:
# 22. find even numbers

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[arr % 2 == 0])

print(arr[np.where(arr % 2 == 0)])

[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [129]:

# 23 . count element greater than 50 

arr = np.array([10,25,60,75,30,90,45])

a = arr[np.where(arr > 50 )]

print(len(a))



3


In [ ]:
# 24. transpose a matrix

arr = np.array([[1,2,3],[4,5,6]])

print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]


In [95]:
# 25 . find row wise sum 


arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr, '\n')

print(np.sum(arr,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[ 6 15 24]


In [ ]:
# 26 . create 5x5 matirx containing numbers from 1 to 25 

data = np.arange(1,26).reshape(5,5)

print(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [112]:
# 27 . replace all odd numbers in an array with -1 

data = np.arange(1,21)


print(np.where(data%2!=0 ,-1,data))

[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


In [122]:
# 28 . find all numbers divisible by 3 

arr = np.arange(1,31)

# print(arr)

print(arr[np.where(arr % 3 == 0)])


[ 3  6  9 12 15 18 21 24 27 30]


In [113]:
# 29  create a random array of 10 integers between 1 and 100

arr = np.random.rand(1,100)

print(arr)

[[0.38793134 0.77282172 0.12591378 0.17833582 0.46352997 0.24694243
  0.64123058 0.88415866 0.19788068 0.71734557 0.55286163 0.80937954
  0.49292315 0.33413062 0.85308165 0.77360853 0.39698988 0.45545007
  0.78838835 0.7619177  0.68413044 0.30489278 0.59793749 0.99036984
  0.31780821 0.18120701 0.434684   0.29599797 0.86887401 0.94451768
  0.42137636 0.92176867 0.02371407 0.05436501 0.0816494  0.39837301
  0.36950108 0.64898887 0.22639918 0.85347133 0.99187201 0.24509562
  0.68533269 0.11359801 0.13563664 0.05541085 0.21938991 0.79483644
  0.77811593 0.85570105 0.97892146 0.77103574 0.41329806 0.9902125
  0.22847865 0.51875502 0.30102431 0.37289452 0.72031949 0.6554579
  0.55424478 0.30096769 0.30233611 0.9046619  0.64887941 0.37314549
  0.36378991 0.23784487 0.53735478 0.39205089 0.46947486 0.37177221
  0.42666076 0.72353736 0.0968642  0.31693779 0.87059247 0.32897883
  0.8490773  0.38016832 0.73210512 0.22467743 0.27083979 0.50194355
  0.18944654 0.75664202 0.24305674 0.49571624 0.31

In [117]:
#30. find the index of the largets element in an array 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,22])

print(np.argmax(arr))

11
