In [ ]:
# logs_Data = np.log(data_1)

# print(logs_Data)


print(f"Square of root :  " ,(data_1 ** 2) )

print( f" Square of root :", (data_2 ** 3 ) )

NameError: name 'data_1' is not defined

In [11]:
import numpy as np 

data = np.array([10,20,30,40,])

result = (data*2)

print(data)

print(result)


[10 20 30 40]
[20 40 60 80]


In [3]:
import numpy as np 

data = np.array([10,20,30,40])

print(data)

print(data.ndim)

[10 20 30 40]
1


In [4]:
np.eye(1,6)

array([[1., 0., 0., 0., 0., 0.]])

In [6]:
data = np.arange(1,26).reshape(5,5)

print(data)

print(data[:2 , 1:5], "\n")
print(data[0:2,0:3] , "\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 2  3  4  5]
 [ 7  8  9 10]] 

[[1 2 3]
 [6 7 8]] 



In [7]:
print(np.random.rand(1,58).shape)

(1, 58)


In [ ]:
np.ones((3,3))

In [ ]:
np.zeros((3,3))

In [ ]:
data = np.arange(1,26).reshape(5,5)

print(data)

print(data[1:2,1:6])

print(data[1:4,1:2])

In [12]:
import numpy as np 

data = np.arange(1,10).reshape(3,3)

data_2 = np.arange(11,20).reshape(3,3)

print(data)

print(data_2)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [15]:
import numpy as np 

print(np.random.rand(3))

[0.88061952 0.42814973 0.29422704]


In [20]:
arr = np.array([1,2,3,4,5,6])

data = np.array([1,2,3,4,5,6,7,8])

print(arr.itemsize)
print(data.itemsize)

8
8


In [ ]:
T = np.array([
    [1,2],
    [3,4]
])

print(T,T)



[[1 2]
 [3 4]] [[1 2]
 [3 4]]


In [23]:
# stype

arr = np.array([1,2,3])

new_arr = arr.astype(float)

print(new_arr)

[1. 2. 3.]


In [ ]:
import numpy as np 

data = np.arange(1,10)



print(data[::-1])



In [ ]:
import numpy as np 

data = np.array([[[10,20,30,40],
                 [50,60,70,80],
                 [20,30,40,50]]])


print(np.sum(data))

print(data.ndim)



In [ ]:
import numpy as np 


data = np.array([
    [ 10,20,30,40],
    [50,60,70,80]])

print(np.sum(data))

print(data.ndim)


In [ ]:
import numpy as np 

data = np.array([10,20,30,40])

print(np.median(data))

In [ ]:
import numpy as np 
from statistics import mode


data = np.array([10,20,30,40,40,40])



print(mode(data))


In [ ]:
import numpy as np 

data = np.array([10,20,30,40])

print(np.mean(data))