In [8]:
import numpy as np 

arr = np.array([[1,2,3,4,5]])

print(arr)

arr



[[1 2 3 4 5]]


array([[1, 2, 3, 4, 5]])

In [ ]:
import numpy as np

import time

n = 100

# LISTS

list1 = list(range(n))
list2 = list(range(n))

start = time.time()

result_list = [list1[i] + list2[i] for i in range(n)]

list_time = time.time() - start

# Numpy Arrays

arr_1 = np.arange(n)
arr_2 = np.arange(n)

start = time.time()

result_arr = arr_1 + arr_2

numpy_time = time.time() - start

print(f"List time :  {list_time:.6f}, sec")
print(f"Numpy Time : {numpy_time:.6f} sec")
print(f"Numpy is approximately {list_time/numpy_time:.2f} x faster")

List time :  17.756028, sec
Numpy Time : 0.357848 sec
Numpy is approximately 49.62 x faster


In [ ]:
list =  np.array([1,2,3,4,5,6])

print(list)

[1 2 3 4 5 6]
3


In [35]:
list_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(list_2)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
list_3 = np.array([[1,2],[3,4],[5,6]])

print(list_3)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
list_3 = np.array([[1,2],[3,4],[5,6]])

print(list_3.shape)
print(list_3.ndim)
print(list_3.size)
print(list_3.dtype)


(3, 2)
2
6
int64


In [49]:
list_4  = np.zeros((2,3),np.int64)

print(list_4)

[[0 0 0]
 [0 0 0]]


In [50]:
list_5  = np.ones((2,3),np.int64)

print(list_4)

[[0 0 0]
 [0 0 0]]
