In [4]:
import numpy as np 

arr = np.array([[1,2,3,4,5]])

print(arr)

arr



[[1 2 3 4 5]]


array([[1, 2, 3, 4, 5]])

In [ ]:
import numpy as np

import time

n = 100

# LISTS

list1 = list(range(n))
list2 = list(range(n))

start = time.time()

result_list = [list1[i] + list2[i] for i in range(n)]

list_time = time.time() - start

# Numpy Arrays

arr_1 = np.arange(n)
arr_2 = np.arange(n)

start = time.time()

result_arr = arr_1 + arr_2

numpy_time = time.time() - start

print(f"List time :  {list_time:.6f}, sec")
print(f"Numpy Time : {numpy_time:.6f} sec")
print(f"Numpy is approximately {list_time/numpy_time:.2f} x faster")

List time :  17.756028, sec
Numpy Time : 0.357848 sec
Numpy is approximately 49.62 x faster


In [ ]:
list =  np.array([1,2,3,4,5,6])

print(list)

[1 2 3 4 5 6]
3


In [35]:
list_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(list_2)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
list_3 = np.array([[1,2],[3,4],[5,6]])

print(list_3)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
list_3 = np.array([[1,2],[3,4],[5,6]])

print(list_3.shape)
print(list_3.ndim)
print(list_3.size)
print(list_3.dtype)


(3, 2)
2
6
int64


In [49]:
list_4  = np.zeros((2,3),np.int64)

print(list_4)

[[0 0 0]
 [0 0 0]]


In [50]:
list_5  = np.ones((2,3),np.int64)

print(list_4)

[[0 0 0]
 [0 0 0]]


In [30]:
# import numpy as np

# # list_6 = np.empty((2,4),np.int64)

# # print(list_6)
# # print(list_6.shape)
# # print(list_6.ndim)
# # print(list_6.size)
# # print(list_6.dtype)

n = 1
m = 6
y = 8

list_7 = np.eye(n,m,dtype=int)

print(list_7)

[[1 0 0 0 0 0]]


In [32]:
data = np.identity((4),dtype=int)

print(data)
print(data.shape)
print(data.ndim)
print(data.size)
print(data.dtype)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
(4, 4)
2
16
int64


In [ ]:
data = np.arange(0,100,2,dtype=int)



print(data)
print(data.shape)
print(data.ndim)
print(data.size)
print(data.dtype)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)
1
50
int64


In [36]:
data =  np.linspace(0.1,1,50,endpoint=True,dtype=float)

print(data)

[0.1        0.11836735 0.13673469 0.15510204 0.17346939 0.19183673
 0.21020408 0.22857143 0.24693878 0.26530612 0.28367347 0.30204082
 0.32040816 0.33877551 0.35714286 0.3755102  0.39387755 0.4122449
 0.43061224 0.44897959 0.46734694 0.48571429 0.50408163 0.52244898
 0.54081633 0.55918367 0.57755102 0.59591837 0.61428571 0.63265306
 0.65102041 0.66938776 0.6877551  0.70612245 0.7244898  0.74285714
 0.76122449 0.77959184 0.79795918 0.81632653 0.83469388 0.85306122
 0.87142857 0.88979592 0.90816327 0.92653061 0.94489796 0.96326531
 0.98163265 1.        ]


In [41]:
data_2 =  np.linspace(0.1,1,50,endpoint=True,retstep=False,dtype=float)

print(data_2)

[0.1        0.11836735 0.13673469 0.15510204 0.17346939 0.19183673
 0.21020408 0.22857143 0.24693878 0.26530612 0.28367347 0.30204082
 0.32040816 0.33877551 0.35714286 0.3755102  0.39387755 0.4122449
 0.43061224 0.44897959 0.46734694 0.48571429 0.50408163 0.52244898
 0.54081633 0.55918367 0.57755102 0.59591837 0.61428571 0.63265306
 0.65102041 0.66938776 0.6877551  0.70612245 0.7244898  0.74285714
 0.76122449 0.77959184 0.79795918 0.81632653 0.83469388 0.85306122
 0.87142857 0.88979592 0.90816327 0.92653061 0.94489796 0.96326531
 0.98163265 1.        ]


In [ ]:

data = np.full(2,3)

print(data)

[3 3]


In [35]:
# a = [1.5,2,3]

a = ['T','F']


data = np.random.choice(a,(10,10),replace=True, p=[0.3,0.7])

print(data)

[['F' 'F' 'F' 'F' 'F' 'F' 'T' 'F' 'F' 'F']
 ['F' 'F' 'T' 'F' 'F' 'F' 'F' 'F' 'F' 'F']
 ['T' 'F' 'F' 'F' 'T' 'F' 'F' 'F' 'T' 'F']
 ['F' 'T' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'F']
 ['F' 'F' 'T' 'T' 'F' 'F' 'T' 'F' 'F' 'T']
 ['F' 'F' 'T' 'F' 'F' 'F' 'F' 'T' 'F' 'F']
 ['T' 'T' 'F' 'F' 'T' 'F' 'F' 'F' 'T' 'F']
 ['F' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'T']
 ['F' 'T' 'F' 'F' 'F' 'F' 'T' 'T' 'F' 'T']
 ['T' 'F' 'F' 'F' 'F' 'T' 'T' 'T' 'F' 'F']]


In [22]:
data_2 = np.random.rand(5)

print(data_2)

[0.05821787 0.52391302 0.8968986  0.36826326 0.98480387]


In [39]:
# data = np.randint(start,stop,shape)

data = np.random.randint(0,10,(2,3))

print(data)



[[3 0 6]
 [2 2 0]]


In [46]:
arr = [1,2,3,4,[5,6,7],8,9]

a = arr[4][1]

print(a)

6


In [48]:
arr = np.array([1,2,3,4,5])

print(arr[1])

2


In [67]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr[0:1, 0:3])

print(arr[0:1 , 1:3])

[[1 2 3]]
[[2 3]]


In [74]:
arr = np.array([1,2,3,4,5,6,7,8,9])

a = [1,2,4]

print(a)

[1, 2, 4]


In [ ]:
arr = np.array([36,44,41,49,46,38,39,45,40])

# a = [arr>20]

# print(a)

# print(arr>20)

a = arr[arr>20]

print(a)



[36 44 41 49 46 38 39 45 40]


In [85]:
arr = np.array([25,35,23,65,3,45,49,22,42])

print(arr+5)
print(arr*5)
print(arr-5)
print(arr/5)
print(arr%5)
print(arr**5)

[30 40 28 70  8 50 54 27 47]
[125 175 115 325  15 225 245 110 210]
[20 30 18 60 -2 40 44 17 37]
[ 5.   7.   4.6 13.   0.6  9.   9.8  4.4  8.4]
[0 0 3 0 3 0 4 2 2]
[   9765625   52521875    6436343 1160290625        243  184528125
  282475249    5153632  130691232]


In [ ]:
arr = np.zeros((5,5))

arr[1:4,1:4] = 1

print(arr)




[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [58]:
a = np.ones((5,5))

a[0:5 , 0:1 ] = 0
a[4:5 , 0:5] = 0

a[0:5 , 4:5 ] = 0

a[0:1 , 0:5 ] = 0

print(a)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [1]:
import numpy as np

In [25]:
import numpy as np
arr = np.array([
        [1,2,3],
        [4,5,6]])

print(arr.flatten(order='C'
                  ))

print(np.ravel(arr,order='A'))



[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr = np.array([
        [1,2,3],
        [4,5,6]])

print(arr.flatten(order='C'  # 
                  ))

print(np.ravel(arr,order='A')) # memory 

print(np.ravel(arr,order='K')) # row wise


print(np.ravel(arr,order='F')) # column wise


# Flatten                 vs          Ravel
# 1. return copy                  1. returns views
# 2. Consume more memory          2. consume less memory
# 3. Slower                       3. Faster
# 4. Original unchange            4. Original will change 





[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [34]:
# iterating through arrays

data = [[[[1,2,3],
          [4,5,6],
          [7,8,9]]]]

# for i in np.nditer(data):
#     print(i)

for i in np.ndenumerate(data):
    print(i)



    

((0, 0, 0, 0), np.int64(1))
((0, 0, 0, 1), np.int64(2))
((0, 0, 0, 2), np.int64(3))
((0, 0, 1, 0), np.int64(4))
((0, 0, 1, 1), np.int64(5))
((0, 0, 1, 2), np.int64(6))
((0, 0, 2, 0), np.int64(7))
((0, 0, 2, 1), np.int64(8))
((0, 0, 2, 2), np.int64(9))


In [48]:
arr =np.array([[1,2,3,4,12,34,],[5,6,7,78,45,8]])

# print(np.split(arr,2
#                ))

print(np.split(arr,2,axis=1))

[array([[1, 2, 3],
       [5, 6, 7]]), array([[ 4, 12, 34],
       [78, 45,  8]])]


In [ ]:
arr =[[[1,2,3,4],
       [5,6,7,8]]]

print(np.transpose(arr))

[[[1]
  [5]]

 [[2]
  [6]]

 [[3]
  [7]]

 [[4]
  [8]]]


In [73]:
# arr = np.array([1,2,3,4,4,4,5,72,8,94,5,6])
# arr = np.array([[9,8,7,6,5,4,3,2,1]])
arr = np.array([[1,2,3,4,5,6,7,8,9]])

# print(np.sort(arr))



print(np.sort(arr,axis=-1,kind='stablesort'))

b = arr[::-1,::-1]

print(b)

[[1 2 3 4 5 6 7 8 9]]
[[9 8 7 6 5 4 3 2 1]]


In [ ]:
# where 

arr = np.array([5,3,1,4])

print(np.where(arr % 2 == 0,5,arr))

print(np.where(arr % 2 != 0 ))



[5 3 1 5]
(array([0, 1, 2]),)


In [89]:
# delete 

# arr = np.array([1,2,3,4,5,6])
arr = np.array([[1,2,3,4,5,6]])

# print(np.delete(arr,1))

print(np.delete(arr,[1,3]))



[1 3 5 6]


In [102]:
# arr = np.arange(1,10).reshape(3,3)

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

# print(np.delete(arr,1, axis=0))

# print(np.delete(arr,1,axis=1))

print(np.delete(arr,np.where(arr > 5)))


[4 5 6 7 8 9]


In [103]:
print(np.where(arr > 5 ))

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))


In [105]:
arr = np.array([1,2,3,4,5])

print(np.insert(arr,[2,5],[20,35]))

[ 1  2 20  3  4  5 35]


In [112]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

# print(np.insert(arr,2,[11,22,33],axis=0))

# print(np.insert(arr, 2, [11,22,33], axis=1))

# print(np.insert(arr, 2, 99, axis=0))

print(np.insert(arr, 2, 99, axis=1))


[[ 1  2 99  3]
 [ 4  5 99  6]
 [ 7  8 99  9]]


In [120]:
arr1 = [1,2,3,4,5]
arr2 = [2,1,6,7,8]

# print(np.intersect1d(arr1,arr2))

print(np.intersect1d(arr1,arr2,assume_unique=True,return_indices=True))



(array([1, 2]), array([0, 1]), array([1, 0]))


In [134]:
from functools import reduce

arr1 = [1,2,3,4,5]
arr2 = [2,1,6,7,8]
arr3 = [9,19,11,12,13]

# print(np.union1d(arr1,arr2))

print(reduce(np.union1d,(arr1,arr2,arr3)))

[ 1  2  3  4  5  6  7  8  9 11 12 13 19]


In [10]:
import numpy as np 

# RESHAPE
data = np.array([2,4,6,8,10,12,14,16,18,20,22,24]).reshape(3,4,order='A') # memory wise axis 
# data = np.array([2,4,6,8,10,12,14,16,18,20,22,24]).reshape(3,4,order='C')  # rows 
# data = np.array([2,4,6,8,10,12,14,16,18,20,22,24]).reshape(3,4,order='F')  #columns 



print(data)






[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [ ]:
# concate

# data = np.array([1,2,3,4,5])
# data_2 = np.array([6,7,8,9,1])

# print(np.concatenate((data,data_2)))

data_1 = np.array([[1,2,3,4],[4,5,6,7]])
data_2 = np.array([[9,8,7,6],[5,4,3,2]])


# print(np.concatenate((data_1,data_2))) # ROW wise

# print(np.concatenate((data_1,data_2),axis=0)) # column wise

print(np.concatenate((data_1,data_2),axis=None)) # ROW wise



[[1 2 3 4]
 [4 5 6 7]
 [9 8 7 6]
 [5 4 3 2]]
[1 2 3 4 4 5 6 7 9 8 7 6 5 4 3 2]


In [30]:
# count non zero 

# data = ([1,2,0,3,4,0,5,6])

data = np.array([[1,2,0,3,4,0,5,6]])

output  = np.count_nonzero(data)
size = len((data))

print("zero count :",size-output)

zero count : -5


In [31]:
arr = np.array([1,2,0,4,0,3,0,4,5,0,6,0])

print(np.unique(arr).size)

7


In [47]:
arr = np.array([0,0,0,2,3,4,0,3,0,0,0])

# print(np.trim_zeros(data))
# print(np.trim_zeros(arr,trim='f')) #front
# print(np.trim_zeros(arr,trim='b')) #back
# print(np.trim_zeros(data,trim='fb'))
print(np.trim_zeros(data,trim='bf'))

[[1 2 0 3 4 0 5 6]]


In [ ]:
arr = np.array([1,2,3,4,5,6])

arr_2 = np.array([6,7,8,9,4,3])

arr_1 = np.copy(arr)

print(arr)

arr3 = arr.view()

print(arr)


# COPY()                   VS              VIEW()

# 1. Independent Memory                1. Shared Memory 
# 2. Slower                            2. Faster
# 3. Original unaffected               3. Original will be affected




[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
arr_1 = np.array([1,2,3,4,5,6])

arr_2 = np.array([4,5,6,7,8,9])

print(np.setxor1d(arr_1,arr_2))

print(np.setdiff1d(arr_1,arr_2))

print(np.dot(arr_1,arr_2))



[1 2 3 7 8 9]
[1 2 3]
154


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [ ]:
# data = np.array([1,2,3,4])

a = np.array([[1,2],[3,4]])


b = np.array([[5,6],[7,8]])


print(np.dot(a,b))

print(np.cross(a,b))




[[19 22]
 [43 50]]
[-4 -4]


C:\Users\shakti\AppData\Local\Temp\ipykernel_3680\1627991354.py:11: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(a,b))


In [ ]:
c = np.array([1,2,3])

d = np.array([4,5,6])

print(np.cross(c,d))

print(c@d)

# it will only work on 1d ARRAY 

[-3  6 -3]
32


In [72]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[7,8,9]])

print(np.cross(a,b))



[[-3  6 -3]
 [-3  6 -3]]
