In [3]:
import numpy as np 

arr = np.array([[1,2,3,4,5]])

print(arr)

arr



[[1 2 3 4 5]]


array([[1, 2, 3, 4, 5]])

In [ ]:
import numpy as np

import time

n = 100

# LISTS

list1 = list(range(n))
list2 = list(range(n))

start = time.time()

result_list = [list1[i] + list2[i] for i in range(n)]

list_time = time.time() - start

# Numpy Arrays

arr_1 = np.arange(n)
arr_2 = np.arange(n)

start = time.time()

result_arr = arr_1 + arr_2

numpy_time = time.time() - start

print(f"List time :  {list_time:.6f}, sec")
print(f"Numpy Time : {numpy_time:.6f} sec")
print(f"Numpy is approximately {list_time/numpy_time:.2f} x faster")

List time :  17.756028, sec
Numpy Time : 0.357848 sec
Numpy is approximately 49.62 x faster


In [ ]:
list =  np.array([1,2,3,4,5,6])

print(list)

[1 2 3 4 5 6]
3


In [35]:
list_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(list_2)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
list_3 = np.array([[1,2],[3,4],[5,6]])

print(list_3)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
list_3 = np.array([[1,2],[3,4],[5,6]])

print(list_3.shape)
print(list_3.ndim)
print(list_3.size)
print(list_3.dtype)


(3, 2)
2
6
int64


In [49]:
list_4  = np.zeros((2,3),np.int64)

print(list_4)

[[0 0 0]
 [0 0 0]]


In [50]:
list_5  = np.ones((2,3),np.int64)

print(list_4)

[[0 0 0]
 [0 0 0]]


In [30]:
# import numpy as np

# # list_6 = np.empty((2,4),np.int64)

# # print(list_6)
# # print(list_6.shape)
# # print(list_6.ndim)
# # print(list_6.size)
# # print(list_6.dtype)

n = 1
m = 6
y = 8

list_7 = np.eye(n,m,dtype=int)

print(list_7)

[[1 0 0 0 0 0]]


In [32]:
data = np.identity((4),dtype=int)

print(data)
print(data.shape)
print(data.ndim)
print(data.size)
print(data.dtype)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
(4, 4)
2
16
int64


In [ ]:
data = np.arange(0,100,2,dtype=int)



print(data)
print(data.shape)
print(data.ndim)
print(data.size)
print(data.dtype)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)
1
50
int64


In [36]:
data =  np.linspace(0.1,1,50,endpoint=True,dtype=float)

print(data)

[0.1        0.11836735 0.13673469 0.15510204 0.17346939 0.19183673
 0.21020408 0.22857143 0.24693878 0.26530612 0.28367347 0.30204082
 0.32040816 0.33877551 0.35714286 0.3755102  0.39387755 0.4122449
 0.43061224 0.44897959 0.46734694 0.48571429 0.50408163 0.52244898
 0.54081633 0.55918367 0.57755102 0.59591837 0.61428571 0.63265306
 0.65102041 0.66938776 0.6877551  0.70612245 0.7244898  0.74285714
 0.76122449 0.77959184 0.79795918 0.81632653 0.83469388 0.85306122
 0.87142857 0.88979592 0.90816327 0.92653061 0.94489796 0.96326531
 0.98163265 1.        ]


In [41]:
data_2 =  np.linspace(0.1,1,50,endpoint=True,retstep=False,dtype=float)

print(data_2)

[0.1        0.11836735 0.13673469 0.15510204 0.17346939 0.19183673
 0.21020408 0.22857143 0.24693878 0.26530612 0.28367347 0.30204082
 0.32040816 0.33877551 0.35714286 0.3755102  0.39387755 0.4122449
 0.43061224 0.44897959 0.46734694 0.48571429 0.50408163 0.52244898
 0.54081633 0.55918367 0.57755102 0.59591837 0.61428571 0.63265306
 0.65102041 0.66938776 0.6877551  0.70612245 0.7244898  0.74285714
 0.76122449 0.77959184 0.79795918 0.81632653 0.83469388 0.85306122
 0.87142857 0.88979592 0.90816327 0.92653061 0.94489796 0.96326531
 0.98163265 1.        ]


In [ ]:

data = np.full(2,3)

print(data)

[3 3]


In [35]:
# a = [1.5,2,3]

a = ['T','F']


data = np.random.choice(a,(10,10),replace=True, p=[0.3,0.7])

print(data)

[['F' 'F' 'F' 'F' 'F' 'F' 'T' 'F' 'F' 'F']
 ['F' 'F' 'T' 'F' 'F' 'F' 'F' 'F' 'F' 'F']
 ['T' 'F' 'F' 'F' 'T' 'F' 'F' 'F' 'T' 'F']
 ['F' 'T' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'F']
 ['F' 'F' 'T' 'T' 'F' 'F' 'T' 'F' 'F' 'T']
 ['F' 'F' 'T' 'F' 'F' 'F' 'F' 'T' 'F' 'F']
 ['T' 'T' 'F' 'F' 'T' 'F' 'F' 'F' 'T' 'F']
 ['F' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'T']
 ['F' 'T' 'F' 'F' 'F' 'F' 'T' 'T' 'F' 'T']
 ['T' 'F' 'F' 'F' 'F' 'T' 'T' 'T' 'F' 'F']]


In [22]:
data_2 = np.random.rand(5)

print(data_2)

[0.05821787 0.52391302 0.8968986  0.36826326 0.98480387]


In [39]:
# data = np.randint(start,stop,shape)

data = np.random.randint(0,10,(2,3))

print(data)



[[3 0 6]
 [2 2 0]]


In [46]:
arr = [1,2,3,4,[5,6,7],8,9]

a = arr[4][1]

print(a)

6


In [48]:
arr = np.array([1,2,3,4,5])

print(arr[1])

2


In [67]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr[0:1, 0:3])

print(arr[0:1 , 1:3])

[[1 2 3]]
[[2 3]]
