In [92]:
import numpy as np

b = np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20],
            [21,22,23,24,25]
            ])

# print(b, "\n")
# print(b.ndim)
# b[1,4] = 100
# b


# 15 + 

# print(b[2:3 , 4: ],"\n")

#  - 6 ,7 11 ,12

# print(b[1:3 , 0:2])

# print(b[-4:-2 , -5:-3], "\n")

# 16,  17 , 21 , 22

# print(b[-1:-3:-1 , -4::-1 ])


# print(b, "\n")

# b[2,1] = 1200

# print(b)


# data = np.arange(1,11)

# data = data[::-1]

# print(data)


a = np.array([1,2,3,4,5])

# print(a[-2:-1])


# a[1],a[2]  = 1000,1000

# a

a[ 1:3] = 1000
a


array([   1, 1000, 1000,    4,    5])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

r = arr[arr % 2 == 0]

print(r)


[ 2  4  6  8 10]


In [ ]:
# ADDITION
arr_2 = np.array([10,20,30,40,50])

print(np.add(arr_2, 10 ))

[20 30 40 50 60]


In [110]:
# SUBSTRACTION

arr_3 = np.array([10,20,30,40])

print(np.subtract(arr_3,2))

[ 8 18 28 38]


In [112]:
# MULTIPLY 

arr_3 = np.array([10,20,30,40])

print(np.multiply(arr_3,2))


[20 40 60 80]


In [ ]:
# DIVIDE 


arr_3 = np.array([10,20,30,40])

print(np.divide(arr_3,2))




[ 5. 10. 15. 20.]


In [114]:
# np.power


arr_3 = np.array([10,20,30,40])

print(np.power(arr_3,2))




[ 100  400  900 1600]


In [116]:
# SQUARE

arr_3 = np.array([10,20,30,40])

print(np.square(arr_3))


[ 100  400  900 1600]


In [ ]:
# absolute

arr_3 = np.array([10,20,30,40])

print(np.abs(arr_3))


[10 20 30 40]


In [121]:
# mod

arr_3 = np.array([10,20,30,40])

print(np.mod(arr_3 ,-11 ))


[-1 -2 -3 -4]
